spring.application.name=IntegrationApplication
maintainx.api-key=${MAINTAINX_API_KEY}

spring.datasource.url=jdbc:postgresql://localhost:5432/maintainx
spring.datasource.username=app
spring.datasource.password=app
spring.jpa.hibernate.ddl-auto=update
